---
- hosts: ws
  become: yes
  become_user: root
  ignore_errors: yes
  tasks:
    - name: Delete Old Artifact
      file:
         path: /opt/qa/spg/*.jar
         state: absent

    - name: Get the PID
      shell: lsof -t -i :8082
      
      register: pid_output
    - name: print pid_output
      debug:
        var: pid_output
      tags:
         - b
    - name: Kill Running App
      shell: "kill -9 {{ pid_output.stdout }}"
      when: pid_output.stdout != ''

    - name: Download New Artifact
      get_url:
        url: http://50.19.53.45:8081/artifactory/geolocation/geo/bio_29.jar
        dest: /opt/qa/spg
        url_username: admin
        url_password: password

    - name: Run the App
      shell: nohup java -jar /opt/qa/spg/*.jar > /opt/qa/spg.log 2>&1 &   